data:
    dataset: LOL
    root: ./data/LOL-v2/Real_captured
    workspace: ./logs/lol-v2-real
    image_size: 128
    num_workers: 16

params:
    loss_weights:
        noise_loss: 1
        # perceptual_loss: 0.1
        image_loss: 1
    # fix_epoch: 40000

model:
    name: DegUNet
    in_channels: 9
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 4
    attn_resolutions: [8, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    patch_n: 4
    batch_size: 6
    n_epochs: 60000
    n_iters: 2000000
    validation_freq: 500

sampling:
    batch_size: 32
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: Adam
    lr: 0.0001
    amsgrad: False
    eps: 0.00000001

lr_scheduler:
    name: MultiStepLR
    kwargs:
        milestones: [5000, 10000, 15000]
        gamma: 0.5
